export const countries = {
  'Argentina': 'ar',
  'Greece': 'gr',
  'Netherlands': 'nl',
  'South Africa': 'za',
  'Australia': 'au',
  'Hong Kong': 'hk',
  'New Zealand': 'nz',
  'South Korea': 'kr',
  'Austria': 'at',
  'Hungary': 'hu',
  'Nigeria': 'ng',
  'Sweeden': 'se',
  'Belgium': 'be',
  'India': 'in',
  'Norway': 'no',
  'Switzerland': 'ch',
  'Brazil': 'br',
  'Indonesia': 'id',
  'Philippines': 'ph',
  'Taiwan': 'tw',
  'Bulgaria': 'br',
  'Ireland': 'ie',
  'Poland': 'pl',
  'Thailand': 'th',
  'Canada': 'ca',
  'Istael': 'il',
  'Portigal': 'pt',
  'Turkey': 'tr',
  'China': 'cn',
  'Italy': 'it',
  'Romania': 'ro',
  'UAE': 'ae',
  'Colombia': 'co',
  'Japan': 'jp',
  'Russia': 'ru',
  'Ukrain': 'ua',
  'Cuba': 'cu',
  'Latvia': 'lv',
  'Saudi Arabia': 'sa',
  'United Kingdom': 'gb',
  'Egypt': 'eg',
  'Malaysia': 'my',
  'Singapore': 'sg',
  'Venuzuela': 've',
  'France': 'fr',
  'Mexico': 'mx',
  'Slovakia': 'sk',
  'Germany': 'de',
  'Morocco': 'ma',
  'Slovenia': 'si'
}

